### ISSUE TITLE
First change to index.html

### ISSUE THREAD

**Issue by jmatos35** [gmvcsc/gmvcsc.github.io#1]
1. Change page title to GMVCSC.
2. Delete image references. Do not delete the images in the repository, just the <img> references in index.html.
3. Delete the header GMVCSC.
4. Delete the header Greater Miami Valley Computer Science Circle.
3. Delete the header "Have a Great Day!"
4. Change the header "Welcome to the GMVMC" to "Welcome to the GMVCSC". 
5. Under the new header "Welcome to the GMVCSC", replace the existing paragraph with the following:

The Greater Miami Valley Computer Science Circle (GMVCSC), in its 3rd year of operation, is an organization dedicated to helping the students of the Miami Valley and beyond. Our Computer circle focuses on computational thinking and problem solving. We use Python/Java/HTML to teach concepts like Algorithm design, Web design, Mobile apps, Robotics, and Information Security. We currently only have 1 class level, as we get more instructors we will try to break out into beginning and intermediate/advanced classes. The GMVCSC is open to 7-12 graders who have had at least Algebra 1. Faculty come from local school districts, area colleges and universities, private industry, local government. We have students from all over the area and beyond; we are truly a “Greater Miami Valley” organization!
We meet from 10:00am-Noon the 1st and 3rd Saturday of the month during the school year (September-early May) in the Mathematical and Microbiological Sciences (MM) Building on the campus of Wright State University.

If you would like to inquire about joining one of our groups, please contact either Mr. Ken Nelson (at ken.nelson@wright.edu) or Dr. Munsup Seoh (at munsup.seoh@wright.edu). Spaces are limited! If there is not space for your child at the time you email us, then you will be placed on our waiting list. Available spaces will be offered to those on our waiting list first, with priority given to those on the list longest.

If you or someone you know, would be interested in volunteering with our organization, then please let us know as well! We will be happy to talk with you and see where your skills and talents can be best used!

Lastly, please let us know if you have any questions and see the flyer about our group copied below. Please share it with anyone who would be interested! We thank you in advance for reading this letter and wish you well!

Coordinators:
Email Mr. Ken Nelson at ken.nelson@wright.edu
Email Dr. Munsup Seoh at munsup.seoh@wright.edu

**Comment by dwcaraway** [comment]
@jmatos35 We might want to find an alternate method of contact. Github (and the web in general) gets mined for email addresses. Would be preferable to use a contact form over published email and have the form go to one or more addresses. Perhaps this could be another task?

Could create a google group and use a google form for the group for contact. Other examples under the Jekyll docs (what Github compiles the site into): https://jekyllrb.com/docs/resources/

**Comment by dwcaraway** [comment]
This one also looks promising, kontactr: https://kontactr.com/

**Comment by jmatos35** [comment]
I see what you are saying. I agree with a contact form. I am going to ask Louis to do that instead.

**Comment by Powerlated** [comment]
I think Discord would work as a great group contact.
